//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SubscribeReqProto.proto
namespace com.game.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubscribeReq")]
  public partial class SubscribeReq : global::ProtoBuf.IExtensible
  {
    public SubscribeReq() {}
    
    private int _subReqID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"subReqID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subReqID
    {
      get { return _subReqID; }
      set { _subReqID = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _productName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"productName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string productName
    {
      get { return _productName; }
      set { _productName = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _address = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> address
    {
      get { return _address; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}