// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: badugipoker.proto

package com.inkstd.badugi.model;

public final class Badugipoker {
  private Badugipoker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userid = 1;
    /**
     * <code>required int32 userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <code>required int32 userid = 1;</code>
     */
    int getUserid();

    // optional string username = 2;
    /**
     * <code>optional string username = 2;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // optional string usernick = 3;
    /**
     * <code>optional string usernick = 3;</code>
     */
    boolean hasUsernick();
    /**
     * <code>optional string usernick = 3;</code>
     */
    java.lang.String getUsernick();
    /**
     * <code>optional string usernick = 3;</code>
     */
    com.google.protobuf.ByteString
        getUsernickBytes();

    // optional bool sex = 4;
    /**
     * <code>optional bool sex = 4;</code>
     */
    boolean hasSex();
    /**
     * <code>optional bool sex = 4;</code>
     */
    boolean getSex();
  }
  /**
   * Protobuf type {@code com.inkstd.badugi.model.LoginInfo}
   */
  public static final class LoginInfo extends
      com.google.protobuf.GeneratedMessage
      implements LoginInfoOrBuilder {
    // Use LoginInfo.newBuilder() to construct.
    private LoginInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginInfo defaultInstance;
    public static LoginInfo getDefaultInstance() {
      return defaultInstance;
    }

    public LoginInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              username_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              usernick_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sex_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_LoginInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_LoginInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inkstd.badugi.model.Badugipoker.LoginInfo.class, com.inkstd.badugi.model.Badugipoker.LoginInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginInfo> PARSER =
        new com.google.protobuf.AbstractParser<LoginInfo>() {
      public LoginInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userid = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userid_;
    /**
     * <code>required int32 userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userid = 1;</code>
     */
    public int getUserid() {
      return userid_;
    }

    // optional string username = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 2;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string usernick = 3;
    public static final int USERNICK_FIELD_NUMBER = 3;
    private java.lang.Object usernick_;
    /**
     * <code>optional string usernick = 3;</code>
     */
    public boolean hasUsernick() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string usernick = 3;</code>
     */
    public java.lang.String getUsernick() {
      java.lang.Object ref = usernick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usernick_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string usernick = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUsernickBytes() {
      java.lang.Object ref = usernick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usernick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool sex = 4;
    public static final int SEX_FIELD_NUMBER = 4;
    private boolean sex_;
    /**
     * <code>optional bool sex = 4;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool sex = 4;</code>
     */
    public boolean getSex() {
      return sex_;
    }

    private void initFields() {
      userid_ = 0;
      username_ = "";
      usernick_ = "";
      sex_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUsernickBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, sex_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUsernickBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, sex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.inkstd.badugi.model.Badugipoker.LoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.inkstd.badugi.model.Badugipoker.LoginInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.inkstd.badugi.model.LoginInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.inkstd.badugi.model.Badugipoker.LoginInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_LoginInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_LoginInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inkstd.badugi.model.Badugipoker.LoginInfo.class, com.inkstd.badugi.model.Badugipoker.LoginInfo.Builder.class);
      }

      // Construct using com.inkstd.badugi.model.Badugipoker.LoginInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        usernick_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_LoginInfo_descriptor;
      }

      public com.inkstd.badugi.model.Badugipoker.LoginInfo getDefaultInstanceForType() {
        return com.inkstd.badugi.model.Badugipoker.LoginInfo.getDefaultInstance();
      }

      public com.inkstd.badugi.model.Badugipoker.LoginInfo build() {
        com.inkstd.badugi.model.Badugipoker.LoginInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.inkstd.badugi.model.Badugipoker.LoginInfo buildPartial() {
        com.inkstd.badugi.model.Badugipoker.LoginInfo result = new com.inkstd.badugi.model.Badugipoker.LoginInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.usernick_ = usernick_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inkstd.badugi.model.Badugipoker.LoginInfo) {
          return mergeFrom((com.inkstd.badugi.model.Badugipoker.LoginInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inkstd.badugi.model.Badugipoker.LoginInfo other) {
        if (other == com.inkstd.badugi.model.Badugipoker.LoginInfo.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000002;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasUsernick()) {
          bitField0_ |= 0x00000004;
          usernick_ = other.usernick_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inkstd.badugi.model.Badugipoker.LoginInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inkstd.badugi.model.Badugipoker.LoginInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userid = 1;
      private int userid_ ;
      /**
       * <code>required int32 userid = 1;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userid = 1;</code>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>required int32 userid = 1;</code>
       */
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userid = 1;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = 0;
        onChanged();
        return this;
      }

      // optional string username = 2;
      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 2;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }

      // optional string usernick = 3;
      private java.lang.Object usernick_ = "";
      /**
       * <code>optional string usernick = 3;</code>
       */
      public boolean hasUsernick() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string usernick = 3;</code>
       */
      public java.lang.String getUsernick() {
        java.lang.Object ref = usernick_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          usernick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string usernick = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUsernickBytes() {
        java.lang.Object ref = usernick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usernick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string usernick = 3;</code>
       */
      public Builder setUsernick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        usernick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string usernick = 3;</code>
       */
      public Builder clearUsernick() {
        bitField0_ = (bitField0_ & ~0x00000004);
        usernick_ = getDefaultInstance().getUsernick();
        onChanged();
        return this;
      }
      /**
       * <code>optional string usernick = 3;</code>
       */
      public Builder setUsernickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        usernick_ = value;
        onChanged();
        return this;
      }

      // optional bool sex = 4;
      private boolean sex_ ;
      /**
       * <code>optional bool sex = 4;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool sex = 4;</code>
       */
      public boolean getSex() {
        return sex_;
      }
      /**
       * <code>optional bool sex = 4;</code>
       */
      public Builder setSex(boolean value) {
        bitField0_ |= 0x00000008;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool sex = 4;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.inkstd.badugi.model.LoginInfo)
    }

    static {
      defaultInstance = new LoginInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.inkstd.badugi.model.LoginInfo)
  }

  public interface UserBaseInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userid = 1;
    /**
     * <code>required int32 userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <code>required int32 userid = 1;</code>
     */
    int getUserid();

    // optional int32 point = 2;
    /**
     * <code>optional int32 point = 2;</code>
     */
    boolean hasPoint();
    /**
     * <code>optional int32 point = 2;</code>
     */
    int getPoint();

    // optional int32 gold = 3;
    /**
     * <code>optional int32 gold = 3;</code>
     */
    boolean hasGold();
    /**
     * <code>optional int32 gold = 3;</code>
     */
    int getGold();

    // optional int32 exp = 4;
    /**
     * <code>optional int32 exp = 4;</code>
     */
    boolean hasExp();
    /**
     * <code>optional int32 exp = 4;</code>
     */
    int getExp();

    // optional int32 vip = 5;
    /**
     * <code>optional int32 vip = 5;</code>
     */
    boolean hasVip();
    /**
     * <code>optional int32 vip = 5;</code>
     */
    int getVip();
  }
  /**
   * Protobuf type {@code com.inkstd.badugi.model.UserBaseInfo}
   */
  public static final class UserBaseInfo extends
      com.google.protobuf.GeneratedMessage
      implements UserBaseInfoOrBuilder {
    // Use UserBaseInfo.newBuilder() to construct.
    private UserBaseInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserBaseInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserBaseInfo defaultInstance;
    public static UserBaseInfo getDefaultInstance() {
      return defaultInstance;
    }

    public UserBaseInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserBaseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              point_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gold_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              exp_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              vip_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_UserBaseInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_UserBaseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inkstd.badugi.model.Badugipoker.UserBaseInfo.class, com.inkstd.badugi.model.Badugipoker.UserBaseInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<UserBaseInfo> PARSER =
        new com.google.protobuf.AbstractParser<UserBaseInfo>() {
      public UserBaseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserBaseInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserBaseInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userid = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userid_;
    /**
     * <code>required int32 userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userid = 1;</code>
     */
    public int getUserid() {
      return userid_;
    }

    // optional int32 point = 2;
    public static final int POINT_FIELD_NUMBER = 2;
    private int point_;
    /**
     * <code>optional int32 point = 2;</code>
     */
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 point = 2;</code>
     */
    public int getPoint() {
      return point_;
    }

    // optional int32 gold = 3;
    public static final int GOLD_FIELD_NUMBER = 3;
    private int gold_;
    /**
     * <code>optional int32 gold = 3;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 gold = 3;</code>
     */
    public int getGold() {
      return gold_;
    }

    // optional int32 exp = 4;
    public static final int EXP_FIELD_NUMBER = 4;
    private int exp_;
    /**
     * <code>optional int32 exp = 4;</code>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 exp = 4;</code>
     */
    public int getExp() {
      return exp_;
    }

    // optional int32 vip = 5;
    public static final int VIP_FIELD_NUMBER = 5;
    private int vip_;
    /**
     * <code>optional int32 vip = 5;</code>
     */
    public boolean hasVip() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 vip = 5;</code>
     */
    public int getVip() {
      return vip_;
    }

    private void initFields() {
      userid_ = 0;
      point_ = 0;
      gold_ = 0;
      exp_ = 0;
      vip_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, point_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, gold_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, exp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, vip_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, point_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gold_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, exp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, vip_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.inkstd.badugi.model.Badugipoker.UserBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.inkstd.badugi.model.Badugipoker.UserBaseInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.inkstd.badugi.model.UserBaseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.inkstd.badugi.model.Badugipoker.UserBaseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_UserBaseInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_UserBaseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.inkstd.badugi.model.Badugipoker.UserBaseInfo.class, com.inkstd.badugi.model.Badugipoker.UserBaseInfo.Builder.class);
      }

      // Construct using com.inkstd.badugi.model.Badugipoker.UserBaseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        point_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        vip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.inkstd.badugi.model.Badugipoker.internal_static_com_inkstd_badugi_model_UserBaseInfo_descriptor;
      }

      public com.inkstd.badugi.model.Badugipoker.UserBaseInfo getDefaultInstanceForType() {
        return com.inkstd.badugi.model.Badugipoker.UserBaseInfo.getDefaultInstance();
      }

      public com.inkstd.badugi.model.Badugipoker.UserBaseInfo build() {
        com.inkstd.badugi.model.Badugipoker.UserBaseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.inkstd.badugi.model.Badugipoker.UserBaseInfo buildPartial() {
        com.inkstd.badugi.model.Badugipoker.UserBaseInfo result = new com.inkstd.badugi.model.Badugipoker.UserBaseInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.point_ = point_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.vip_ = vip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.inkstd.badugi.model.Badugipoker.UserBaseInfo) {
          return mergeFrom((com.inkstd.badugi.model.Badugipoker.UserBaseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.inkstd.badugi.model.Badugipoker.UserBaseInfo other) {
        if (other == com.inkstd.badugi.model.Badugipoker.UserBaseInfo.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasPoint()) {
          setPoint(other.getPoint());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasVip()) {
          setVip(other.getVip());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.inkstd.badugi.model.Badugipoker.UserBaseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.inkstd.badugi.model.Badugipoker.UserBaseInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userid = 1;
      private int userid_ ;
      /**
       * <code>required int32 userid = 1;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userid = 1;</code>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>required int32 userid = 1;</code>
       */
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userid = 1;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = 0;
        onChanged();
        return this;
      }

      // optional int32 point = 2;
      private int point_ ;
      /**
       * <code>optional int32 point = 2;</code>
       */
      public boolean hasPoint() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 point = 2;</code>
       */
      public int getPoint() {
        return point_;
      }
      /**
       * <code>optional int32 point = 2;</code>
       */
      public Builder setPoint(int value) {
        bitField0_ |= 0x00000002;
        point_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 point = 2;</code>
       */
      public Builder clearPoint() {
        bitField0_ = (bitField0_ & ~0x00000002);
        point_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gold = 3;
      private int gold_ ;
      /**
       * <code>optional int32 gold = 3;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 gold = 3;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>optional int32 gold = 3;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000004;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gold = 3;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gold_ = 0;
        onChanged();
        return this;
      }

      // optional int32 exp = 4;
      private int exp_ ;
      /**
       * <code>optional int32 exp = 4;</code>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 exp = 4;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>optional int32 exp = 4;</code>
       */
      public Builder setExp(int value) {
        bitField0_ |= 0x00000008;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exp = 4;</code>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        exp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 vip = 5;
      private int vip_ ;
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public boolean hasVip() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public int getVip() {
        return vip_;
      }
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public Builder setVip(int value) {
        bitField0_ |= 0x00000010;
        vip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public Builder clearVip() {
        bitField0_ = (bitField0_ & ~0x00000010);
        vip_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.inkstd.badugi.model.UserBaseInfo)
    }

    static {
      defaultInstance = new UserBaseInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.inkstd.badugi.model.UserBaseInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inkstd_badugi_model_LoginInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_inkstd_badugi_model_LoginInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inkstd_badugi_model_UserBaseInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_inkstd_badugi_model_UserBaseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021badugipoker.proto\022\027com.inkstd.badugi.m" +
      "odel\"L\n\tLoginInfo\022\016\n\006userid\030\001 \002(\005\022\020\n\010use" +
      "rname\030\002 \001(\t\022\020\n\010usernick\030\003 \001(\t\022\013\n\003sex\030\004 \001" +
      "(\010\"U\n\014UserBaseInfo\022\016\n\006userid\030\001 \002(\005\022\r\n\005po" +
      "int\030\002 \001(\005\022\014\n\004gold\030\003 \001(\005\022\013\n\003exp\030\004 \001(\005\022\013\n\003" +
      "vip\030\005 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_inkstd_badugi_model_LoginInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_inkstd_badugi_model_LoginInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_inkstd_badugi_model_LoginInfo_descriptor,
              new java.lang.String[] { "Userid", "Username", "Usernick", "Sex", });
          internal_static_com_inkstd_badugi_model_UserBaseInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_inkstd_badugi_model_UserBaseInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_inkstd_badugi_model_UserBaseInfo_descriptor,
              new java.lang.String[] { "Userid", "Point", "Gold", "Exp", "Vip", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
